### ISSUE TITLE
"Submit comments & approve" is shown for change that is already approved/merged

### ISSUE THREAD

**Issue by dpursehouse** [chungwu/gmail-gerrit#12]
When a change has been merged, and someone adds a comment afterwards, replying to that comment from the Gmail/Inbox client shows "Submit comments & approve" button which doesn't really make sense in this context.

<img width="619" alt="screen shot 2018-03-19 at 16 18 25" src="https://user-images.githubusercontent.com/836426/37582677-72e36214-2b91-11e8-910d-cc77b178fa5c.png">

**Comment by chungwu** [comment]
Hmm I think approving after merge could make sense (if the change was merged without your +2, but you still want to express your approval)...

**Comment by dpursehouse** [comment]
Fair point.
