### ISSUE TITLE
How to debug the extension

### ISSUE THREAD

**Issue by wedi** [chungwu/gmail-gerrit#13]
Hi!
Unfortunately the extension does not work for me. Neither in the standard gmail nor in inbox.
Can you explain me how to debug the extension or what kind of information you need?

**Comment by chungwu** [comment]
Could you reload the Gmail tab, and paste the content of the javascript console? Thanks!

**Comment by wedi** [comment]
The problem is, that the gerrit search operator `assignee:self` is invalid. Maybe my instance of gerrit does not support it? Removing this in options makes it work. 👍 

```
gmgt.js:275 Function call: {"type":"loadChanges","url":"https://developer.locoslab.com/gerrit"} 
{success: false, status: 400, err_msg: "Unsupported operator assignee:self"}
err_msg: "Unsupported operator assignee:self"
status: 400
success: false
__proto__: Object
```

**Comment by chungwu** [comment]
Good to know!  I've removed `assignee:self` from the default inboxQuery as it's not supported till later versions of Gerrit.  Thanks for the report!
