### ISSUE TITLE
Code review header shown for non-code-review email

### ISSUE THREAD

**Issue by dpursehouse** [chungwu/gmail-gerrit#14]
I'm seeing this on a mail that was sent to the jgit development mailing list:

<img width="612" alt="screen shot 2018-05-17 at 7 59 08" src="https://user-images.githubusercontent.com/836426/40148357-7e64e21c-59a8-11e8-98ef-e07f476fdf76.png">

Somehow it's detecting a review there and displaying the header, even though it isn't a mail from Gerrit.

**Comment by dpursehouse** [comment]
Link to the mail on the jgit-dev public archive:

https://dev.eclipse.org/mhonarc/lists/jgit-dev/msg03574.html

**Comment by chungwu** [comment]
Ah this is a bug in how we're extracting the change id from the email thread. For each email thread, the extension looks for links to the Gerrit host, and then takes the ending number as the change id. In this case, there's a reply to the referenced thread that includes a link to https://git.eclipse.org/r/c/122288/2, which was extracted as change #2 displayed in the Gerrit header. (if you're reading this response in Inbox, you'll likely see the same thing again!)
