### ISSUE TITLE
Cannot get to work with https://gerrit-review.googlesource.com

### ISSUE THREAD

**Issue by sschuberth** [chungwu/gmail-gerrit#4]
I cannot get the extension to work with the Gerrit instance hosting Gerrit itself (https://gerrit-review.googlesource.com). I always see *Error: Cannot authenticate* next to my mail, though when I click on the *Login* I'm correctly logged in right away.

**Comment by sschuberth** [comment]
The log shows:

    Running Gerrit plugin! DEV YO
    Function call: {"type":"authenticate"} Object
    Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
    Gmail in mode thread
    Found change 72147
    Not authenticated! authenticate first...
    Function call: {"type":"authenticate"} Object
    Still failed to authenticate :'(
    Loaded change Object
    Gmail in mode threadlist
    Not authenticated! authenticate first...
    Function call: {"type":"authenticate"} Object
    Still failed to authenticate :'(

**Comment by chungwu** [comment]
Ah it looks like the version of gerrit there is no longer embedding the csrf token in the html page, but is instead setting it in a cookie. The chrome extension will need cookie permission and read it out of the cookie instead.

**Comment by chungwu** [comment]
I've pushed a few fixes and uploaded a new version of the extension.  Please give it a try and see if it works for you!

**Comment by sschuberth** [comment]
Works for me now, thanks a lot!
