### ISSUE TITLE
Support for Inbox

### ISSUE THREAD

**Issue by dpursehouse** [chungwu/gmail-gerrit#7]
I've just tried the extension, and it seems to work well when I view my emails via gmail.com, however I normally use inbox.google.com and it doesn't seem to do anything there.

Do you have any plan to support Inbox?

Thanks!

**Comment by chungwu** [comment]
No plans at the moment, since I don't use Inbox and they are quite different...  But I'll take a look and see how easy or hard it'd be!

**Comment by chungwu** [comment]
Hmm actually this doesn't look too bad; I'll try to hack something together when I can 🙂

**Comment by chungwu** [comment]
@dpursehouse well, that was a rabbit hole that was hard to get out of...  I just pushed v0.3.0, which includes Google Inbox support!  Please give it a try and see if it works for you.

**Comment by dpursehouse** [comment]
@chungwu thanks for the quick response.  I've just updated it and it now seems to be recognizing Gerrit emails in Inbox!

I haven't tried to comment on any changes yet.  The only thing I've seen so far that looks odd is "unavailable..." shown in several places next to the line numbers, and a couple of "Line undefined".

**Comment by dpursehouse** [comment]
<img width="672" alt="screen shot 2018-02-23 at 16 04 14" src="https://user-images.githubusercontent.com/836426/36582084-59a5c7b0-18b3-11e8-8e17-a0e5e4a85043.png">

<img width="351" alt="screen shot 2018-02-23 at 16 05 36" src="https://user-images.githubusercontent.com/836426/36582103-6f45750c-18b3-11e8-8b61-a164a8d0cfc2.png">

**Comment by chungwu** [comment]
Indeed -- a known issue, see https://github.com/chungwu/gmail-gerrit/issues/8.  Will get to fixing that one of these nights :-)
