### ISSUE TITLE
For file line comments in `Gerrit-MessageType: comment` emails, sometimes the referenced line shows up as "unavailable"

### ISSUE THREAD

**Issue by chungwu** [chungwu/gmail-gerrit#8]
This happens if a line comment is made on an earlier patch set than the one referenced by `Gerrit-PatchSet` in that email.  Currently at the time we try to render the comment thread, we only have the file contents for the `Gerrit-PatchSet` loaded, so lines from other patch sets are "unavailable".  We should lazily try to load file contents from other patch sets as necessary.

**Comment by chungwu** [comment]
An example provided by @dpursehouse:

<img src="https://user-images.githubusercontent.com/836426/36582084-59a5c7b0-18b3-11e8-8e17-a0e5e4a85043.png">

**Comment by dpursehouse** [comment]
Thanks.  This has fixed it for some of the cases, but I'm still seeing "undefined" in some places.

See here for example.  The ones reported before are fixed, but there is still one showing as `Line undefined: undefined`

<img width="493" alt="screen shot 2018-02-27 at 14 32 28" src="https://user-images.githubusercontent.com/836426/36712242-39f78ee2-1bcb-11e8-9436-f581f1df6942.png">

**Comment by chungwu** [comment]
Arrug, that is a file comment (not a line comment)... Will fix :-)

**Comment by chungwu** [comment]
Okay this should be fixed in 0.3.3 :-)

**Comment by dpursehouse** [comment]
Awesome.  Thanks for the quick response.

<img width="424" alt="screen shot 2018-02-27 at 17 01 14" src="https://user-images.githubusercontent.com/836426/36717039-dad7322c-1bdf-11e8-8708-6edb3800bda7.png">

**Comment by chungwu** [comment]
Great! Thanks for the bug reports 😁
